In [13]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import pickle

In [14]:
df = pd.read_csv("treated_dataset.csv")

In [15]:
df

,title,254,507,882,1424,1435,1733,1903,2033,2110,...,275020,275970,276463,276680,277427,277478,277639,278137,278188,278418
0,1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1033,You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1034,Zen and the Art of Motorcycle Maintenance: An ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1035,Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1036,"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# Uses csr_matrix from scipy.spacer
input_matrix = csr_matrix(df.drop('title',axis=1))

In [17]:
input_matrix

<1037x1628 sparse matrix of type '<class 'numpy.float64'>'
	with 25570 stored elements in Compressed Sparse Row format>

In [18]:
#NearestNeighbors and fit
nn = NearestNeighbors(algorithm="brute")
nn.fit(input_matrix)

NearestNeighbors(algorithm='brute')

In [19]:
distances, recommendation = nn.kneighbors(df.iloc[1032,1:].values.reshape(1,-1),n_neighbors=6)

In [20]:
##f.iloc[recommendation]

for i in range(len(recommendation)):
    print(df.iloc[recommendation[i],0])

1032                                      Year of Wonders
1007                             Where or When  : A Novel
964     Tom Clancy's Op-Center: Games of State (Tom Cl...
501                                         No Safe Place
317                                Ground Zero and Beyond
950                                        Thousand Acres
Name: title, dtype: object

In [21]:
pickle.dump(nn,open('pkl_store/model.pkl','wb'))
pickle.dump(df['title'],open('pkl_store/book_names.pkl','wb'))
pickle.dump(df,open('pkl_store/pivot_table.pkl','wb'))

In [22]:
df

,title,254,507,882,1424,1435,1733,1903,2033,2110,...,275020,275970,276463,276680,277427,277478,277639,278137,278188,278418
0,1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1033,You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1034,Zen and the Art of Motorcycle Maintenance: An ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1035,Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1036,"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# output function

In [67]:
def recommendation_system(input_book_title):
    book_index = np.where(df['title'] == input_book_title)[0]

    if len(book_index) == 0:
        print("this book does not exist on our list.")
        return
    
    book_index = book_index[0]
    _, recomm = nn.kneighbors(df.iloc[book_index,1:].values.reshape(1,-1),n_neighbors=6)
    for i in recomm[0]:
        if i == 0:
            print(f'you selected the book: {input_book_title}')
            print('the recommendations are: ')
            print('')
        else: 
            print(df.iloc[i]['title'])

In [59]:
#_, test = nn.kneighbors(df.iloc[np.where(df['title'] == '1984')[0][0],1:].values.reshape(1,-1),n_neighbors=6)
#recommendation_system('Zoya')
np.where(df['title'] == '1984')[0]

array([0], dtype=int64)

In [64]:
df.iloc[0]['title']

'1984'

In [69]:
recommendation_system('Zoya')

Zoya
The Ranch
Fine Things
Morning, Noon &amp; Night
Tom Clancy's Op-Center: Games of State (Tom Clancy's Op Center (Paperback))
The Best Laid Plans

In [73]:
test

array([[1035,  876,  275,  469,  964,  704]], dtype=int64)